### ISSUE TITLE
Autosave not working when disconnecting Teensy

### ISSUE THREAD

**Issue by Baegus** [derkyjadex/M8WebDisplay#13]
When I close the browser tab, disconnect my Teensy, reconnect it and then reopen the tab, all my work is restored. However, if I don't close the window and disconnect Teensy, my work is discarded.

Would it possible to autosave at this point as well?

**Comment by jakerr** [comment]
In my understanding, disconnecting the Teensy from the computer will remove it from power, so at that point it would be too late to trigger an autosave.

**Comment by derkyjadex** [comment]
It isn't possible to trigger anything on the Teensy _after_ the USB has been removed, since there's no way of communicating with it and it won't have any power anyway. Neither the Teensy nor your computer know that you are about to remove the USB plug, so there's nothing we can do _beforehand_ either.

The only way this could possibly work is if there was some kind of periodic autosave, eg. every 30 seconds, or 5 minutes. This is something that would be entirely for the M8 firmware to handle and not something we can control over serial from the web page.
