### ISSUE TITLE
Chrome, Steam Deck: 'No compatible devices found'

### ISSUE THREAD

**Issue by mike-kelly** [derkyjadex/M8WebDisplay#29]
I managed to `make run` successfully on the Steam Deck, which I believe is based on Arch Linux. However when I hit the 'Connect' button in the Chrome webpage, the dialog window shows:

> ...://localhost:8000 wants to connect to a serial port
> No compatible devices found

The Teensy/M8 is otherwise recognised by the machine. I can see it in the system volume controls, qpwgraph, and it seems to be listed as `/dev/ttyACM0`, where the ownership is root:uucp

I added the Steam Deck user to the `uucp` group, but it seems that Chrome can't see the device.

**Comment by derkyjadex** [comment]
Does it work correctly when you go to https://derkyjadex.github.io/M8WebDisplay/? If not then running it locally probably won't work either, but potentially makes it less likely to work (because of the way Chrome decides whether a domain can be trusted).

After adding yourself to the new group you need to log out and back in again for it to be picked up. I don't know how the Steam Deck is set up, but a full reboot will certainly do it. If the Teensy still doesn't show up in Chrome after that than I'm not sure where to look next.

There is a Reddit post where someone appears to have got it working by (re) installing libserialport, https://www.reddit.com/r/SteamDeck/comments/113aqud/is_there_a_way_to_have_a_serial_connection/. I can't vouch for whether those instructions are safe/a good idea.

**Comment by mike-kelly** [comment]
No it also doesn't work on your github hosted site. 
The group membership is fine. Libserialport is installed.
It seems to be a Chrome/serial port access thing, maybe specific to Archlinux. I thought it might be my USB adaptor, based on that Reddit post, but as the M8 device shows up fine in other programmes on the Steam Deck, e.g. qpwgraph, that seems very unlikely. I also tested it working on my desktop computer.

**Comment by derkyjadex** [comment]
I'm not sure I can help any more with this issue and I don't think there's anything I can do within this project to fix the issue, so I'm going to close this.

Feel free to re-open if you think there's a bug that needs fixing, or perhaps some documentation that could be added that would help someone else.

**Comment by RAOEUS** [comment]
I believe this is something to do with the flathub build of Chromium (when installed from the "Discover" application). I installed Chromium with the nix package manager, and it works flawlessly, now.
